### ISSUE TITLE
How the forgotpassword working?

### ISSUE THREAD

**Issue by aneeshsudhakaran** [DevMarketer/multiauth_tutorial#11]
Hi  Dev,

Thank you for this tutorials. Its really very helpful.
I didn't get the reset password email.

getting error 

"InvalidArgumentException
Route [password.reset] not defined."

Thanks in advance
Aneesh

**Comment by jacurtis** [comment]
Do you have a route in your routes file for the password reset route?

The error says you don't have a route setup

**Comment by aneeshsudhakaran** [comment]
Yes i have...
I have to send seperate emails for user and admin for  forgot passwords.
Is this work in your demo code?

Thanks for the quick reply.

**Comment by aneeshsudhakaran** [comment]
![screenshot-2017-10-25 laravel](https://user-images.githubusercontent.com/22345127/32011416-5e804ea8-b9d2-11e7-963f-f9ba6168e4fb.png)

How we can manage seperate forgotpassword for admin and user.
(I'm using this tutorial)

**Comment by aneeshsudhakaran** [comment]
Hi Dev,

I got the soln from your video.
https://youtu.be/jNdVW8lsFOo


Thx alot!!!!!
