### ISSUE TITLE
Admin login fail

### ISSUE THREAD

**Issue by krasidankov** [DevMarketer/multiauth_tutorial#22]
Hello everyone. When I want to login as an administrator in the admin login it is showing error. I am posting a screenshot of the error. This is Laravel 5.6.
![screenshot 101](https://user-images.githubusercontent.com/40579668/44629082-c1e19900-a952-11e8-9de6-530da9003561.png)

If someone knows the solution, please share it. Thank you.

**Comment by juliosouzam** [comment]
Hey man, have you sure do you imported facade Auth in your project?

**Comment by krasidankov** [comment]
I have been doing everything the same from the videos and it doesn't work. This is the repository to see the full code. https://github.com/krasidankov/laravel-multi-auth

**Comment by krasidankov** [comment]
I managed somehow to fix the problem. I just put 'use Illuminate\Support\Facades\Auth;' at the top and it worked.
P.S.: I'm new to Laravel and this maybe a really stupid mistake.
