### ISSUE TITLE
Csrf token issue 

### ISSUE THREAD

**Issue by nirojmagar** [DevMarketer/multiauth_tutorial#24]
when admin is logged in and then 
login user on new tab of same browser 
then logout to user and 
then logout admin 

the it says : 
The page has expired due to inactivity.
Please refresh and try again.

**Comment by ghost** [comment]
Both the User logout and the Admin logout are using the `GET` method. No reason to use a form to submit to the logout route. You can just insert a anchor tag with the following to get the user/admin to logout.

`<a href="{{ route('user.logout') }}>User Logout</a>`
`<a href="{{ route('admin.logout') }}>Admin Logout</a>`
