### ISSUE TITLE
When Admin log out that time visible  Admin log in page 

### ISSUE THREAD

**Issue by mostafa6765** [DevMarketer/multiauth_tutorial#3]
When Admin` Log out` the page redirect to `home page`.how can redirect `admin log in page` when `admin log out`.

**Comment by liakat89** [comment]
login from two different browser one for user and another for admin and test again! hope it helps

**Comment by jatin222** [comment]
You can't comment at this time — your comment cannot be blank.

**Comment by cham11ng** [comment]
Solution is to overwrite the logout function,
Add following lines in AdminLoginController

```php
class AdminLoginController extends Controller {
    //
    /**
     * Log the user out of the application.
     * Redirect to admin login page
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function logout(Request $request)
    {
        $this->guard()->logout();

        $request->session()->flush();

        $request->session()->regenerate();

        return redirect('/admin'); // default is 'redirect('/')'
    }
    //
}
```

**Comment by jacurtis** [comment]
Thank you for specifying that @cham11ng. That is the correct solution.

New video going live May 22 addresses creating a specific logout function exclusively for each type of user. In the video we add the redirect line and I leave it at the `return redirect('/');` but of course you can always customize that route that you want to redirect, to be anything your application requires.

Code for the video has been updated and you can view the changelog here: 
https://github.com/DevMarketer/multiauth_tutorial/commit/558bc66d783841c724cc556679fa9218f184c3f2?diff=split
